# Define Constants here

X = 0
Y = 1
Z = 2
PRESENCE = 3

# Body Position Indices:
MP_SHOULDER_L = 11
MP_ELBOW_L = 13
MP_HAND_L = 15
MP_FINGER1_L = 17
MP_FINGER2_L = 19

MP_HIPS_L = 23
MP_KNEES_L = 25
MP_ANKLE_L = 27
MP_HEEL_L = 29
MP_TOE_L = 31

MP_SHOULDER_R = 12
MP_ELBOW_R = 14
MP_HAND_R = 16
MP_FINGER1_R = 18
MP_FINGER2_R = 20

MP_HIPS_R = 24
MP_KNEES_R = 26
MP_ANKLE_R = 28
MP_HEEL_R = 30
MP_TOE_R = 32

# Rotation Indices for return rotation list
MP_SHOULDER_L_ROTATION = 0
MP_ELBOW_L_ROTATION = 1
MP_HAND_L_ROTATION = 2
MP_HIPS_L_ROTATION = 3
MP_KNEE_L_ROTATION = 4
MP_FOOT_L_ROTATION = 5
MP_SHOULDER_R_ROTATION = 6
MP_ELBOW_R_ROTATION = 7
MP_HAND_R_ROTATION = 8
MP_HIPS_R_ROTATION = 9
MP_KNEE_R_ROTATION = 10
MP_FOOT_R_ROTATION = 11
MP_ROOT_ROTATION = 12

MP_SPINE_ROTATION = 13
MP_SPINE3_ROTATION = 14


